import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class NoteCreate {
  @ApiProperty()
  title: string;
  @ApiProperty()
  content: string;
}

export class Note {
  @ApiProperty()
  id: number;
  @ApiProperty()
  title: string;
  @ApiProperty()
  content: string;
}
